<?php
/**
 * Created by PhpStorm.
 * User: nddang196
 * Date: 21-10-2017
 * Time: 08:29 SA
 */

class Dangnd_Album_Block_Adminhtml_Image_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    public function __construct()
    {
        parent::__construct();

        $this->setId('editItemFrm');
        $this->setTitle(Mage::helper('dangnd_album')->__('Information'));
    }

    public function _prepareForm()
    {
        $model = Mage::registry('imageModel');
        $albums = Mage::getModel('dangnd_album/image')->getCollection();
        $menuSelect = array();

        foreach ($albums as $item)
        {
            $menuSelect[] = array(
                'value' => $item->getId(),
                'label' => $item->getName()
            );
        }

        $form = new Varien_Data_Form(array(
            'id'      => 'edit_form',
            'action'  => $this->getData('action'),
            'method'  => 'post'
        ));

        $fieldset = $form->addFieldset('base', array(
            'ledend' => Mage::helper('dangnd_album')->__('Information')
        ));
        $fieldset->addField('albumId', 'select', array(
            'name'   => 'albumId',
            'label'  => Mage::helper('dangnd_album')->__('Album'),
            'values' => $menuSelect
        ));
        $fieldset->addField('title', 'text', array(
            'name'     => 'title',
            'label'    => Mage::helper('dangnd_album')->__('Title'),
            'class'    => 'required-entry',
            'required' => true
        ));
        $fieldset->addField('link', 'text', array(
            'name'     => 'link',
            'label'    => Mage::helper('dangnd_album')->__('Link'),
            'class'    => 'required-entry',
            'required' => true
        ));

        if ($model->getId())
        {
            $fieldset->addField('id', 'hidden', array(
                'name' => 'id',
            ));
        }

        $form->addValues($model->getData());
        $form->setUseContainer(true);
        $form->setAction($this->getUrl('*/image/save'));

        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}