<?php
$std = $this->getData('std');
$err = $this->getData('err');
?>

<div>
    <a id="btn-back" href="<?= Mage::getUrl('assignment6') ?>">Back</a>
</div>
<div class="container">
    <h1>Update</h1>
    <form method="post">
        <div style="text-align: center; color : red">
            <?php echo (isset($err)) ? $err : '' ?>
        </div>
        <div class="frm-group">
            <div class="lb">
                <lable>Name</lable>
            </div>
            <input class="inp" type="text" name="name"
                   value="<?php if (isset($std['name'])) echo $std['name'] ?>" required>
        </div>

        <div class="frm-group">
            <div class="lb">
                <lable>E-mail</lable>
            </div>
            <input class="inp" type="email" name="email"
                   value="<?php if (isset($std['email'])) echo $std['email'] ?>" required>
        </div>

        <div class="frm-group">
            <div class="lb">
                <lable>Address</lable>
            </div>
            <input class="inp" type="text" name="address"
                   value="<?php if (isset($std['address'])) echo $std['address'] ?>" required>
        </div>

        <div class="frm-group">
            <div class="lb">
                <lable>Phone</lable>
            </div>
            <input class="inp" type="text" name="phone"
                   value="<?php if (isset($std['phone'])) echo $std['phone'] ?>" required>
        </div>

        <div class="frm-group" style="text-align: center; margin-top : 30px">
            <input type="hidden" name="require" value="update">
            <button type="submit">luu</button>
        </div>
    </form>
</div>
