<html>
<head>
    <meta charset='UTF-8'>
    <title>Assignment 6 - 1</title>
    <style>
        .container {
            width       : 60%;
            margin-left : 20%;
            margin-top  : 50px;
            border: 1px black solid;
            padding: 20px 20px 20px 20px;
        }

        h1 {
            text-align : left;
            color      : red;
        }

        table {
            border-collapse : collapse;
            width           : 100%;
            margin-top      : 30px
        }

        th, td {
            text-align : left;
            padding    : 8px;
        }

        tr:nth-child(even) { background-color : #f2f2f2 }

        th {
            background-color : blue;
            color            : white;
        }

        #add {
            padding          : 10px 20px;
            background-color : green;
            color            : white;
            margin           : 20px 0;
            float: right;
        }
        .btn{
            text-decoration  : none;
            border-radius    : 10px;
            font-weight      : bold;
        }

        .btn-update {
            padding          : 5px;
            border           : 1px darkgrey solid;
            border-radius    : 10px;
            background-color : green;
            color: white;
        }
        .btn-delete {
            padding          : 5px;
            border           : 1px darkgrey solid;
            border-radius    : 10px;
            background-color : red;
            color: white;
        }
    </style>
</head>

<body>
<div class="container">
    <h1>List Student</h1>
    <div>
        <a href='<?php echo Mage::getUrl('asign61/index/formAdd'); ?>' class='btn' id='add'>Thêm</a>
    </div>
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Addreess</th>
            <th>Action</th>
        </tr>
        </thead>

        <tbody>
        <?php
        if (empty($data)) {
            echo '<td colspan="6">Empty!!</td>';
        } else {
            foreach ($data as $sinhvien) { ?>
                <tr>
                    <td><?php echo $sinhvien->name;?></td>
                    <td><?php echo $sinhvien->email;?></td>
                    <td><?php echo $sinhvien->address;?></td>
                    <td>
                        <a href='<?php echo Mage::getUrl('asign61/index/formUpdate/id/'.$sinhvien->sinhvien_id); ?>' class='btn btn-update'>Update</a>
                        <a href='<?php echo Mage::getUrl('asign61/index/delete/id/'.$sinhvien->sinhvien_id); ?>' class='btn btn-delete'>Delete</a>
                    </td>
                </tr>
            <?php }
        }
        ?>
        </tbody>
    </table>
</div>
</body>
</html>