<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HTML5 Register Form</title>
    <style>
        :-moz-placeholder {
            color: blue;
        }

        ::-webkit-input-placeholder {
            color: blue;
        }
        *:focus {outline: none;}
        .register_form{
            padding-left: 300px;
        }
        #my_form{
            border: 1px black solid;
        }
        }
        body {font: 14px/21px "Lucida Sans", "Lucida Grande", "Lucida Sans Unicode", sans-serif;}

        .register_form h2, .register_form label {font-family:Georgia, Times, "Times New Roman", serif;}

        .form_hint, .required_notification {font-size: 11px;}

        .register_form ul {
            width:750px;
            list-style-type:none;
            list-style-position:outside;
            margin:0px;
            padding:0px;
        }
        .register_form li{
            padding:12px;
            border-bottom:1px solid #eee;
            position:relative;
        }
        .register_form li:first-child, .register_form li:last-child {
            border-bottom:1px solid #777;
        }
        .register_form label {
            width:150px;
            margin-top: 3px;
            display:inline-block;
            float:left;
            padding:3px;
        }
        .register_form input {
            height:20px;
            width:220px;
            padding:5px 8px;
        }
        .register_form textarea {padding:8px; width:300px;}
        .register_form button {margin-left:156px;}

        .register_form input, .register_form textarea {
            border:1px solid #aaa;
            box-shadow: 0px 0px 3px #ccc, 0 10px 15px #eee inset;
            border-radius:2px;
        }
        .register_form input:focus, .register_form textarea:focus {
            background: #fff;
            border:1px solid #555;
            box-shadow: 0 0 3px #aaa;
        }
        /* Button Style */
        button.submit {
            background-color: #68b12f;
            background: -webkit-gradient(linear, left top, left bottom, from(#68b12f), to(#50911e));
            background: -webkit-linear-gradient(top, #68b12f, #50911e);
            background: -moz-linear-gradient(top, #68b12f, #50911e);
            background: -ms-linear-gradient(top, #68b12f, #50911e);
            background: -o-linear-gradient(top, #68b12f, #50911e);
            background: linear-gradient(top, #68b12f, #50911e);
            border: 1px solid #509111;
            border-bottom: 1px solid #5b992b;
            border-radius: 3px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            -ms-border-radius: 3px;
            -o-border-radius: 3px;
            box-shadow: inset 0 1px 0 0 #9fd574;
            -webkit-box-shadow: 0 1px 0 0 #9fd574 inset ;
            -moz-box-shadow: 0 1px 0 0 #9fd574 inset;
            -ms-box-shadow: 0 1px 0 0 #9fd574 inset;
            -o-box-shadow: 0 1px 0 0 #9fd574 inset;
            color: white;
            font-weight: bold;
            padding: 6px 20px;
            text-align: center;
            text-shadow: 0 -1px 0 #396715;
        }
        button.submit:hover {
            opacity:.85;
            cursor: pointer;
        }
        button.submit:active {
            border: 1px solid #20911e;
            box-shadow: 0 0 10px 5px #356b0b inset;
            -webkit-box-shadow:0 0 10px 5px #356b0b inset ;
            -moz-box-shadow: 0 0 10px 5px #356b0b inset;
            -ms-box-shadow: 0 0 10px 5px #356b0b inset;
            -o-box-shadow: 0 0 10px 5px #356b0b inset;
    </style>
</head>
<body>
<div id="my_form">
    <form class="register_form" action="<?php echo Mage::getUrl('asign61/index/update/id/'.$data->sinhvien_id); ?>" method="post" name="register_form">
        <ul>
            <li>
                <h2>Register<h2>
            </li>
            <li>
                <label for="name">Name:</label>
                <input type="text" name="name" value="<?php echo $data->name;?>" required/>
            </li>
            <li>
                <label for="address">Address:</label>
                <input type="text" name="address" value="<?php echo $data->address;?>" required/>
            </li>
            <li>
                <label for="email">Email:</label>
                <input type="email" name="email" value="<?php echo $data->email;?>" placeholder="youremail@example.com" required/>
            </li>
            <li>
                <button class="submit" type="submit">Submit Form</button>
            </li>
        </ul>
    </form>
</div>
</body>
</html>