<!DOCTYPE html>
<html>
<head>
	<title>hello world title</title>
	<style type="text/css">
		.header{border: 1px solid red;padding:10px;text-align: center;margin-bottom:5px;}
		.main{border: 1px solid red;padding:10px;text-align: center;margin-bottom:5px;}
		.footer{border: 1px solid red;padding:10px;text-align: center;margin-bottom:5px;}
		.logo{border: 1px solid black;padding:10px;text-align: center;float:left;}
		.mainl{border: 1px solid green;float:left;margin-right: 10px;padding:10px;width:30%;height:400px;}
		.mainc{border: 1px solid green;float:left;margin-right: 10px;padding:10px;width:30%;height:400px;}
		.mainr{border: 1px solid green;float:left;padding:10px;width:30%;height:400px;}
		.mainb{clear: both;}
		.logo{width:30%;text-align:center;}
		.logol{clear: both;}
		.A,.B,.C,.D{border: 1px solid yellow;padding:10px;text-align: center;}
		.A,.B{width:30%;}
	</style>
</head>
<body>
	<div class="header"><?php echo $this->getChildHtml('block_header'); ?>
		<div class="logo">logo</div>
		<div class="logol"></div>
	</div>
 	<div class="main">
 		<div class="mainl"><?php echo $this->getChildHtml('block_mainl'); ?>
 			<div class="C">C</div>
 		</div>
 		<div class="mainc"><?php echo $this->getChildHtml('block_mainc'); ?>
 			<div class="A">A</div>
 			<div class="B">B</div>
 		</div>
 		<div class="mainr"><?php echo $this->getChildHtml('block_mainr'); ?>
 			<div class="D">D</div>
 		</div>
 		<div class="mainb"></div>
 	</div>
 	<div class="footer"><?php echo $this->getChildHtml('block_footer'); ?></div>
 </body>
</html>
