<?php
/**
 * Created by PhpStorm.
 * User: nddang196
 * Date: 21-10-2017
 * Time: 08:29 SA
 */

class Dangnd_MegaMenu_Block_Adminhtml_Menu_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    public function __construct()
    {
        parent::__construct();

        $this->setId('menuFrm');
        $this->setTitle(Mage::helper('megamenu')->__('Menu Information'));
    }

    public function _prepareForm()
    {
        $model = Mage::registry('menumodel');

        $form = new Varien_Data_Form(array(
            'id'     => 'edit_form',
            'action' => $this->getData('action'),
            'method' => 'post'
        ));
        $yesno = array(
            array(
                'value' => 0,
                'label' => Mage::helper('megamenu')->__('No')
            ),
            array(
                'value' => 1,
                'label' => Mage::helper('megamenu')->__('Yes')
            )
        );

        $fieldset = $form->addFieldset('base', array(
            'ledend' => Mage::helper('megamenu')->__('Menu Information')
        ));
        $fieldset->addField('name', 'text', array(
            'name'     => 'name',
            'label'    => Mage::helper('megamenu')->__('Name'),
            'class'    => 'required-entry',
            'required' => true
        ));
        $fieldset->addField('type', 'select', array(
            'name'   => 'type',
            'label'  => Mage::helper('megamenu')->__('Type'),
            'values' => array(
                array(
                    'value' => 'horizontal',
                    'label' => Mage::helper('megamenu')->__('Horizontal')
                ),
                array(
                    'value' => 'vertical',
                    'label' => Mage::helper('megamenu')->__('Vertical')
                )
            )
        ));
        $fieldset->addField('active', 'select', array(
                'name'   => 'active',
                'label'  => Mage::helper('megamenu')->__('Active'),
                'values' => $yesno
            )
        );

        if ($model->getId())
        {
            $fieldset->addField('id', 'hidden', array(
                'name' => 'id',
            ));
        }

        $form->addValues($model->getData());
        $form->setUseContainer(true);
        $form->setAction($this->getUrl('*/megaMenu/save'));

        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}