<div class="" style="padding-bottom:120px">
    <form action="" method="POST"">
    <div class="">
        <label>MSSV</label>
        <input class="form-control" name="mssv" placeholder="Please Enter Name" />
    </div>
    <div class="">
        <label>Name</label>
        <input class="form-control" name="name" placeholder="Please Enter Name" />
    </div>
    <div class="">
        <label>Email</label>
        <input type="email" class="form-control" name="email" placeholder="Please Enter Email" />
    </div>
    <div class="">
        <label>Phone</label>
        <input type="number" class="form-control" name="phone" placeholder="Please Enter Phone" />
    </div>
    <div class="">
        <label>Date</label>
        <input type="date" class="form-control" name="date"/>
    </div>
    <button type="submit" name="submit" class="">User Add</button>
    <button type="reset" class="">Reset</button>
    <form>
</div>