<table class="">
    <thead>
    <tr align="center">
        <th>ID</th>
        <th>MSSV</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Birthday</th>
        <th>Edit</th>
        <th>Del</th>
    </tr>
    </thead>
    <tbody>
    <tr class="" align="center">
        <td>{{$student->id}}</td>
        <td>{{$student->mssv}}</td>
        <td>{{$student->name}}</td>
        <td>{{$student->email}}</td>
        <td>{{$student->phone}}</td>
        <td>{{$student->birthday}}</td>
        <td class="center"><i class=""></i> <a href="">Edit</a></td>
        <td class="center"><i class=""></i><a href=""> Delete</a></td>
    </tr>
    </tbody>
</table>