<html>
<head>
	<title>Trang chu</title>
</head>
<body>
    <div >
        <?php echo $this->getChildHtml('blockd')?>
    </div>

    <div style="width: 100%;float: left;">
       <?php echo $this->getChildHtml('blocka')?>
        <?php echo $this->getChildHtml('blockc')?>
        <?php echo $this->getChildHtml('blockb')?>
    </div>
    <div>
        <?php echo $this->getChildHtml('blocke')?>
    </div>
 </body>
</body>
</html>