<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Thiết kế web với bootstrap</title>
    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="css/styles.css">
</head>
<body>
<div class="container">
    <nav class="nav nav-pills nav-justified">
        <ul>
            <li><a href="" title="">Logo <?php echo $this->getChildHtml('logo') ?></a></li>
            <li><a href="" title="">
                    <?php
                        echo "Header " . $this->getMyName();
                    ?>
                    <?php echo $this->getChildHtml('headers') ?>

                </a></li>
        </ul>
    </nav>
    <div class="col-md-3 text-center">
        Left Bar <?php echo $this->getChildHtml('lefts') ?>
    </div>
    <div class="col-md-6 text-center">

        Content   <?php echo $this->getChildHtml('contents') ?>

    </div>
    <div class="col-md-3 text-center">
        Right Bar <?php echo $this->getChildHtml('rights') ?>
    </div>
</div>
<div class="container clearfix text-center">
    Footer <?php echo $this->getChildHtml('footers') ?>
</div>
</body>
</html>
