<style>
    body {
        border: none;
    }
    .header, .footer {
        height: 100px;
        display: block;
        clear: both;
        text-align: center;
        border: 1px solid black;
        padding: 10px;
    }
    .left, .content, .right {
        float: left;
        text-align: center;
        border: 1px solid black;
        padding: 10px;
    }
    .left, .right {
        width: 21%;
        text-align: center;
        border: 1px solid black;
        padding: 10px;
    }
    .content {
        width: 50%;
        text-align: center;
        border: 1px solid black;
        padding: 10px;
    }
    .blocka, .blockb, .blockc, .blockd, .logo {
        width: 40px;
        text-align: center;
        border: 1px solid black;
        padding: 10px;
    }

</style>
<?php echo $this->getChildHtml('header') ?>
<div class="left">
    <?php echo $this->getChildHtml('left') ?>
    LEFT
</div>
<div class="content">
    <?php echo $this->getChildHtml('content') ?>
    CONTENT
</div>
<div class="right">
    <?php echo $this->getChildHtml('right') ?>
    RIGHT
</div>
<?php echo $this->getChildHtml('footer') ?>
