<html>
<head>
    <style>
        .header{
            width: 100%;
            height: 200px;
            clear: both;
            background-color: red;
        }
        .left{
            width: 20%;
            float: left;
            height: 200px;
            background-color: blue;
        }
        .content{
            width: 80%;
            height: 200px;
            float: left;
            background-color: pink;
        }
        .footer{
            width: 100%;
            height: 200px;
            clear: both;
            background-color: red;
        }

    </style>
</head>
<body>
<div class="header"><?php echo $this->getChildHtml('c2_header'); ?></div>
<div class="left"><?php echo $this->getChildHtml('c2_left'); ?></div>
<div class="content"><?php echo $this->getChildHtml('c2_content'); ?></div>
<div class="footer"><?php echo $this->getChildHtml('c2_footer'); ?></div>
</body>
</html>

