<div class="container">
    <div class="col-lg-6">
        <div class="panel panel-primary">
        <section class="panel">
            <header class="panel-heading">
                Them Sinh vien
            </header>
            <div class="panel-body">
                <form role="form" method="post">
                    <div class="form-group">
                        <label for="name">Ten Sinh Vien</label>
                        <input type="text" class="form-control" id="name"  name="name">
                    </div>

                    <div class="form-group">
                        <label for="lop">Lop</label>
                        <input type="text" class="form-control" id="lop"  name="lop">
                    </div>

                    <div class="form-group">
                        <label for="birth">Ngay sinh</label>
                        <input type="date" class="form-control" id="birth" name="birth">
                    </div>
                    <button type="submit" name="submit" class="btn btn-info">Submit</button>
                    <a class="btn btn-warning" href="http://mageosc.local/sinhvien/index/index" title="">Cancel</a>
                </form>
            </div>
        </section>
        </div>
    </div>
</div>