<div class="col-xs-12 col-md-12 col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading " id="my-header">Sinh Vien</div>
        <div class="panel-body">
            <a href="http://mageosc.local/sinhvien/index/insert" class="btn btn-primary">Them Sinh Vien</a>
            <div class="bootstrap-table">
                <div class="table-responsive">

                    <table class="table table-bordered" style="margin-top:20px;">
                        <thead>
                        <tr class="bg-primary">
                            <th width="4%" >#</th>
                            <th width="10%" >Ten SV</th>
                            <th width="10%" >Lop</th>
                            <th width="10%" >Ngay sinh</th>
                            <th width="10%" >Tùy Chọn</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td id="list-p"></td>
                            <td>
                                <a id='width' href="" class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i>Edit</a>
                                <a id='width' href="" onclick="return confirm('Are you delete this product ?')" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
