<?php
$std = $this->getData('std');
$err = $this->getData('err');
?>

<style>
    .container {
        width       : 60%;
        margin-left : 20%;
        margin-top  : 50px;
    }

    h1 { text-align : center; color : blue }

    form {
        padding       : 30px;
        border        : 5px #4dbeff solid;
        border-radius : 5px;
        width         : 100%;
    }

    .frm-group {
        width   : 100%;
        margin  : 15px 0;
        padding : 10px;
        clear   : both;
    }

    .lb {
        width      : 25%;
        float      : left;
        text-align : right;
    }

    .inp {
        width        : 50%;
        margin-right : 10%;
        height       : 30px;
        float        : right;
    }

    button {
        padding     : 15px 40px;
        background  : #75ff56;
        color       : #fff;
        font-weight : bold;
    }

    button:hover {
        cursor     : pointer;
        background : #0eff1d;
    }

    #btn-back {
        padding     : 15px 40px;
        background  : #fff4a2;
        color       : #fff;
        font-weight : bold;
    }

    #btn-back:hover {
        cursor     : pointer;
        background : #ffed63;
    }
</style>
<div>
    <a id="btn-back" href="<?= Mage::getUrl('asm61') ?>">Back</a>
</div>
<div class="container">
    <h1>Update Information Student</h1>
    <form method="post">
        <div style="text-align: center; color : red">
            <?php echo (isset($err)) ? $err : '' ?>
        </div>
        <div class="frm-group">
            <div class="lb">
                <lable>Name</lable>
            </div>
            <input class="inp" type="text" name="name"
                   value="<?php if (isset($std['name'])) echo $std['name'] ?>" required>
        </div>

        <div class="frm-group">
            <div class="lb">
                <lable>E-mail</lable>
            </div>
            <input class="inp" type="email" name="email"
                   value="<?php if (isset($std['email'])) echo $std['email'] ?>" required>
        </div>

        <div class="frm-group">
            <div class="lb">
                <lable>Address</lable>
            </div>
            <input class="inp" type="text" name="address"
                   value="<?php if (isset($std['address'])) echo $std['address'] ?>" required>
        </div>

        <div class="frm-group">
            <div class="lb">
                <lable>Phone</lable>
            </div>
            <input class="inp" type="text" name="phone"
                   value="<?php if (isset($std['phone'])) echo $std['phone'] ?>" required>
        </div>

        <div class="frm-group" style="text-align: center; margin-top : 30px">
            <input type="hidden" name="require" value="update">
            <button type="submit">Save</button>
        </div>
    </form>
</div>
