<?php
/**
 * Created by PhpStorm.
 * User: nddang196
 * Date: 21-10-2017
 * Time: 08:29 SA
 */

class Dangnd_MegaMenu_Block_Adminhtml_Item_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    public function __construct()
    {
        parent::__construct();

        $this->setId('itemFrm');
        $this->setTitle(Mage::helper('megamenu')->__('Item Information'));
    }

    public function _prepareForm()
    {
        $model = Mage::registry('itemmodel');
        $editor = Mage::getSingleton('cms/wysiwyg_config');
        $menu = Mage::getModel('megamenu/menu')->getCollection();
        $menuSelect = array();

        foreach ($menu as $item)
        {
            $menuSelect[] = array(
                'value' => $item->getId(),
                'label' => $item->getName()
            );
        }

        $form = new Varien_Data_Form(array(
            'id'     => 'edit_form',
            'action' => $this->getData('action'),
            'method' => 'post'
        ));

        $fieldset = $form->addFieldset('base', array(
            'ledend' => Mage::helper('megamenu')->__('Item Information')
        ));
        $fieldset->addField('title', 'text', array(
            'name'     => 'title',
            'label'    => Mage::helper('megamenu')->__('Title'),
            'class'    => 'required-entry',
            'required' => true
        ));
        $fieldset->addField('link', 'text', array(
            'name'     => 'link',
            'label'    => Mage::helper('megamenu')->__('Link'),
            'class'    => 'required-entry',
            'required' => true
        ));
        $fieldset->addField('class', 'text', array(
            'name'     => 'class',
            'label'    => Mage::helper('megamenu')->__('Class'),
            'class'    => 'required-entry',
            'required' => true
        ));
        $fieldset->addField('parent', 'select', array(
            'name'     => 'parent',
            'label'    => Mage::helper('megamenu')->__('Parent'),
            'values'   => $menuSelect
        ));
        $fieldset->addField('content', 'editor', array(
            'name'     => 'content',
            'label'    => Mage::helper('megamenu')->__('Content'),
            'class'    => 'required-entry',
            'required' => true,
            'wysiwyg'  => true,
            'config'   => $editor
        ));

        if ($model->getId())
        {
            $fieldset->addField('id', 'hidden', array(
                'name' => 'id',
            ));
        }

        $form->addValues($model->getData());
        $form->setUseContainer(true);
        $form->setAction($this->getUrl('*/megaItem/save'));

        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    protected function _prepareLayout()
    {
        parent::_prepareLayout();

        if (Mage::getSingleton('cms/wysiwyg_config')->isEnabled())
        {
            $this->getLayout()->getBlock('head')->setCanLoadTinyMce(true);
        }
    }
}