<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="js/jquery-1.11.1.min.js"></script>
    <style>
        body {
            padding-top: 0px;
        }
        .form-control {
            margin-bottom: 10px;
        }
        .login-screen-bg {
            background-color: #EFEFEF;
        }
    </style>
</head>
<body>

<div class="well">
</div>
<div class="container"></div><div class="row"></div><div class="col-md-2"></div><div class="col-md-3"></div><div class="col-md-4"></div><div class="container" style="margin-top:20px;">
    <div class="row">
        <div class="col-lg-12">

            <div class="media">
                <a href="#" class="pull-left">
                    <img alt="64x64" data-src="holder.js/64x64" class="media-object img-thumbnail" style="width: 64px; height: 64px;" src="http://placehold.it/64x64">
                </a>
                <div class="media-body">
                    <h3 class="media-heading"><strong><a href="#">name</a></strong></h3>
                    <p class="small">name<span class="glyphicon glyphicon-time timestamp" data-toggle="tooltip" data-placement="bottom" title="Lundi 24 Avril 2014 à 18h25"></span> il y a 12 jours</p>
                </div>
            </div>

            <div class="media">
                <a href="#" class="pull-left">
                    <img alt="64x64" data-src="holder.js/64x64" class="media-object img-thumbnail" style="width: 64px; height: 64px;" src="http://placehold.it/64x64">
                </a>
                <div class="media-body">
                    <h3 class="media-heading"><strong><a href="#">email</a></strong></h3>
                    <p class="small">email<span class="glyphicon glyphicon-time timestamp" data-toggle="tooltip" data-placement="bottom" title="Lundi 24 Avril 2014 à 18h25"></span> il y a 12 jours</p>
                </div>
            </div>

        </div>
    </div>
</div>
</body>
</html>